### ISSUE TITLE
Update Landing Page

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/cube#1]
# Faces of the Cube
We should display a two-dimensional, clickable, cube that contains the following faces:
- National Curriculum
- Cybersecurity Topics
- Academics
- Mapping
- Modality
- National Cyber Academy

## Active Faces
These faces will be active; meaning that when the user clicks one of these the effects described below will occur. 

**Academics**
Clicking this face will replace the search bar and cube with a listing of learning objects, separated by institution level. This will contain the SPLASH course under the K-12 category and Cybersecurity for Future Presidents under the Undergraduate category. _This is a low priority for the NCCP Workshop._

**Mapping**
Clicking this face will open the side panel allowing the user to search for standards published by NCWF, CAE, etc... Once the search button in the panel is clicked, the landing page will disappear and the results of the search by mapping will appear listed on screen.

**Modality**
Clicking this face, for now, will contain the curriculum listings as they appear at the moment (separated by types). When these listings appear they will replace the search bar and cube on screen.

**Comment by DonSeannelly** [comment]
# Defining Search Functionality

In addition to adding the cube faces, the search bar in the nav bar should be moved into the body of the page. When the user opens the landing page they should see the search bar and the two-dimensional faces of the cube under it.

## What Happens When Searching
- When searching in the search bar the cube should disappear and show the search results.
- Upon clearing the search field the cube should reappear and there should be no more listings on screen.

**Comment by DonSeannelly** [comment]
Refer to NCWF, CAE, etc... as "source"

**Comment by gshaw1997** [comment]
Add Breadcrumbs component for routing with the CUBE.

**Comment by DonSeannelly** [comment]
## Status
- [ ] Build Academics Component
- [ ] Build Mapping Component
- [ ] Build Modality Component
- [ ] Add Breadcrumbs 
- [ ] Design Clickable Cube in Home Component

**Comment by siddharthkaza** [comment]
Spell out CLARK in the header - CLARK - Cybersecurity Labs and Resource Knowledge-base
Then add links after - Replace "Home" with "Search"
