### ISSUE TITLE
As a user, I want to browse CLARK

### ISSUE THREAD

**Issue by gshaw1997** [Cyber4All/cube#12]
**So that...**
1. ~~I can view all learning objects uploaded via Bloomin' Onion.~~
2. ~~I can find learning objects based on a specific set of filters.~~
3. ~~I can view recommended learning objects based on specific metrics.~~
4. ~~I can search learning objects based on its name.~~
5. ~~I perform a broad search on LearningObjects~~

**Comment by DonSeannelly** [comment]
0274b9f completes story 1.

**Comment by tylernhoward** [comment]
**Note to complete this issue:**
In the learningObject database:
Metrics(likes and downloads) must be a property of learningObjects.
Filters (academic level and etc..) must be a property of learningObjects

The suggestion API also needs to suggest objects for the mapping

**Comment by gshaw1997** [comment]
https://github.com/Cyber4All/database-interaction/commit/7a01318836e7898a59e12cd09c1ba669e04dbba6 closes user story 2.

**Comment by gshaw1997** [comment]
https://github.com/Cyber4All/cube/commit/0c344cbb0145380168ebb12ad1d1a1029de6c18a closes user story 4 & 5.
