### ISSUE TITLE
Logging In

### ISSUE THREAD

**Issue by EVogel1999** [Cyber4All/cube#31]
I am not sure if this is a bug or whatever but last night I logged into CLARK and didn't sign out when I was finished.  I did this because I wanted to see if the next day it would ask for my login information again.  It didn't, it still had me logged in.  Not sure If I didn't leave the website long enough for it to be a significance or if this "issue" completely irrelevant.

**Comment by nrwinner** [comment]
This is actually correct behavior, we're storing the user data in what's called a "session" and only forcing a login when the user either doesn't have a token or when that token has expired.
