### ISSUE TITLE
filtering by standard outcomes not working for mapped module

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/cube#47]
I entered a module (search "responsible") mapped to a CS2013 objective. I select that objective, but the module result is filtered out. See screens. 
<img width="1265" alt="screen shot 2018-02-19 at 9 02 54 pm" src="https://user-images.githubusercontent.com/2423261/36404492-f55091ca-15b8-11e8-843c-44eb68f22907.png">
<img width="1184" alt="screen shot 2018-02-19 at 9 07 06 pm" src="https://user-images.githubusercontent.com/2423261/36404493-f55a74c4-15b8-11e8-8d5b-b11764d6756a.png">

**Comment by gshaw1997** [comment]
Closed in https://github.com/Cyber4All/database-interaction/commit/a98bc848d224bfe1747936775ead4a4441cdc7d0
