### ISSUE TITLE
As a user, I want to have a cart

### ISSUE THREAD

**Issue by gshaw1997** [Cyber4All/cube#9]
**So that...**
1. ~~I can add to list of learning objects I want to download. (State management/Add to cart)~~
2. ~~I can remove learning objects from the list (of learning objects) I want to download. (State management/Remove from cart)~~
3. ~~I can download a zip file of learning objects I want. (Checkout)~~
4. I can save learning objects that I want to download at another time. (Save for later)

**Comment by DonSeannelly** [comment]
Closing as story 4 has been converted to a standalone issue (#18)
